    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 687, in step
    self.goto_motor()

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 687, in step
    self.goto_motor()

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 687, in step
    self.goto_motor()

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 687, in step
    self.goto_motor()

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 687, in step
    self.goto_motor()

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 687, in step
    self.goto_motor()

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 687, in step
    self.goto_motor()

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 687, in step
    self.goto_motor()

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 225, in _MOVVEL
    self.XY_c.MOVVEL(Xs[:2], V[:2])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 114, in MOVVEL
    l.MOV(1, x)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcscommands.py", line 3106, in MOV
    self.__msgs.send(cmdstr)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702

GCSError: Position out of limits (7)

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 225, in _MOVVEL
    self.XY_c.MOVVEL(Xs[:2], V[:2])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 114, in MOVVEL
    l.MOV(1, x)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcscommands.py", line 3106, in MOV
    self.__msgs.send(cmdstr)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702

GCSError: Position out of limits (7)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 687, in step
    self.goto_motor()

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 687, in step
    self.goto_motor()

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 225, in _MOVVEL
    self.XY_c.MOVVEL(Xs[:2], V[:2])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 114, in MOVVEL
    l.MOV(1, x)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcscommands.py", line 3106, in MOV
    self.__msgs.send(cmdstr)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702

GCSError: Position out of limits (7)

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 225, in _MOVVEL
    self.XY_c.MOVVEL(Xs[:2], V[:2])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 114, in MOVVEL
    l.MOV(1, x)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcscommands.py", line 3106, in MOV
    self.__msgs.send(cmdstr)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702

GCSError: Position out of limits (7)

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 225, in _MOVVEL
    self.XY_c.MOVVEL(Xs[:2], V[:2])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 114, in MOVVEL
    l.MOV(1, x)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcscommands.py", line 3106, in MOV
    self.__msgs.send(cmdstr)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)

  File "C:\Users\Local_Admin\Anaconda3\lib\site-packages\pipython-1.3.4.59-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702

GCSError: Position out of limits (7)

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 399, in save_corrections
    np.savetxt(fn, self.zcoeff )

OSError: [Errno 9] Bad file descriptor

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Unable to move to position

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\application_interface.py", line 680, in goto_motor
    [s.getValue() for s in self.motor_selectors])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 106, in goto_position
    self._MOVVEL(Xs, V, checkid=checkid)

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 226, in _MOVVEL
    self.Z_c.MOVVEL(Xs[2:], V[2:])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 270, in MOVVEL
    self.move_to(X[0])

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\controllers\stage_controller.py", line 317, in move_to
    self._kCubeDCServoMotor.MoveTo(Decimal(float(pos)), timeout);

DeviceMovingException: Device already moving
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyDeviceMovement(Int32 functionDepth, VerifyMovementFlags flags)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.MoveTo(Decimal position, Int32 waitTimeout)

Traceback (most recent call last):

  File "C:\Users\Local_Admin\Desktop\twoPhotonsController\source\mouvment_delegate.py", line 403, in load_corrections
    with open(fn,'r') as f:

OSError: [WinError 6] The handle is invalid



Unable to set shutter time 0.1
Unable to set shutter time 0.1
Unable to set shutter time 0.09198708369814117
Unable to set shutter time 0.1